name: tictactoe
description: "A Tic Tac Toe game with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_bloc: ^9.1.0
  
  # Model classes
  freezed_annotation: ^3.1.0
  
  # Navigation
  go_router: ^15.1.2
  flutter_hooks: ^0.21.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.10.4
  freezed: ^3.2.3

dependency_overrides:
  analysis_server_plugin: ^0.2.0
  analyzer: ^8.1.0

flutter:
  uses-material-design: true
